application: timecard1129
version: 1
runtime: go
api_version: go1

handlers:
- url: /(.*\.html)$
  static_files: static/\1
  upload: static/.*\.html$

- url: /js/
  static_dir: static

- url: /bower_components/
  static_dir: bower_components


- url: /api/admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always


- url: /api/.*
  script: _go_app
  login: required
  secure: always

- url: /.*
  script: _go_app
  login: required
  secure: always
